// File generated by the FlutterFire CLI -- but hand-seeded here since this
// session can't run an interactive `flutterfire configure` login.
//
// ACTION REQUIRED before first run:
//   1. dart pub global activate flutterfire_cli
//   2. flutterfire configure --project=solesync-f7740
//   This registers new Android/iOS apps under the existing "SoleSync"
//   Firebase project (the same one the Vue app uses) and overwrites this
//   file with the real `appId`/`apiKey` values for each platform, plus
//   drops `google-services.json` / `GoogleService-Info.plist` in place.
//
// Until you do that, `android` and `ios` below are empty placeholders and
// Firebase.initializeApp() will throw.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Same web config the Vue app uses (project: solesync-f7740).
  static const web = FirebaseOptions(
    apiKey: 'AIzaSyAAxqGViLFzxcHZSVkcavsK3paSaI6xjNo',
    authDomain: 'solesync-f7740.firebaseapp.com',
    projectId: 'solesync-f7740',
    storageBucket: 'solesync-f7740.firebasestorage.app',
    messagingSenderId: '158134545545',
    appId: '1:158134545545:web:851c003a5740265dddea58',
  );

  // TODO(flutterfire configure): replace with the real Android app values.
  static const android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '158134545545',
    projectId: 'solesync-f7740',
    storageBucket: 'solesync-f7740.firebasestorage.app',
  );

  // TODO(flutterfire configure): replace with the real iOS app values.
  static const ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '158134545545',
    projectId: 'solesync-f7740',
    storageBucket: 'solesync-f7740.firebasestorage.app',
    iosBundleId: 'com.solesync.solesync',
  );
}
